name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up Miniconda
          uses: conda-incubator/setup-minicinda@v3
          with:
            environment-file: env.yml
            activate-environment: env
            python-version: 3.10

        - name: Check Conda environment
          run: conda list

        - name: Verify packages
          run: pytest tests/
            python -c "import numpy, pandas, sklearn; print("Packages installed successfully") 
        
       
