name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create environment from file
        run: conda env create -f env.yml

      - name: Activate environment
        run: conda Activate env
        
      - name: Check Conda environment
        run: conda list

      - name: Verify packages
        run: |
            call activate env
            conda list numpy
            conda list pandas
            conda list sklearn
            print("Packages installed successfully") 
        
       
